language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - master

before_install:
  - go get github.com/PuerkitoBio/goquery
  - go get github.com/fatih/color
  - go get github.com/hashicorp/go-getter
  - go get github.com/hashicorp/go-version
  - go get github.com/urfave/cli
  - go get github.com/stretchr/testify/assert

script:
  - go test -v ./...
