#!/bin/bash

fxtbenv_parse_profile () {
    profile=$(echo $1 | cut -d'-' -f2)
    case $profile in
	*@*)
	    echo $profile
	    return 0
	    ;;
	*)
	    echo $profile
	    return 1
	    ;;
    esac
}

fxtbenv_parse_product () {
    product=$(echo $1 | cut -d'-' -f1)
    echo $product
}

if [ -z "$FXTBENV_DISABLE_ANSICOLOR" ]; then
    FXTBENV_DISABLE_ANSICOLOR=0
fi

FXTBENV_CREATE_PROFILE_DIR=0

fxtbenv_list () {
    for profile_dir in $FXTBENV_HOME/firefox/profiles $FXTBENV_HOME/thunderbird/profiles; do
	for profile in `ls -1 $profile_dir`; do
	    if [ $FXTBENV_PROFILE = "$profile" ]; then
		printf "%3s %s %s\n" " *" $profile
	    else
		printf "%3s %s\n" "" $profile
	    fi
	done
    done
}

fxtbenv_usage_use () {
    echo "$(fxtbenv_name): fxtbenv use [--create|-c] firefox-VERSION@PROFILE"
    echo "$(fxtbenv_name): fxtbenv use [--create|-c] thunderbird-VERSION@PROFILE"
}

fxtbenv_name () {
    if [ $FXTBENV_DISABLE_ANSICOLOR -eq 1 ]; then
	echo "fxtbenv"
    else
	echo "\e[37m\e[42mfxtbenv\e[0m"
    fi
}

fxtbenv_warning () {
    if [ $FXTBENV_DISABLE_ANSICOLOR -eq 1 ]; then
	echo "warning"
    else
	echo "\e[37m\e[43mwarning\e[0m"
    fi
}

fxtbenv_error () {
    if [ $FXTBENV_DISABLE_ANSICOLOR -eq 1 ]; then
	echo "$1"
    else
	echo "\e[37m\e[41m$1\e[0m"
    fi
}

fxtbenv () {
    if [ -z "$FXTBENV_HOME" ]; then
	export FXTBENV_HOME=$HOME/.fxtbenv
    fi
    case $1 in
	use)
	    shift
	    target=""
	    while [ $# -gt 0 ]; do
		case $1 in
		    --create|-c)
			FXTBENV_CREATE_PROFILE_DIR=1
			;;
		    firefox-*|thunderbird-*)
			target=$1
			;;
		    *)
			echo "$(fxtbenv_name):  invalid argument: $(fxtbenv_error $1)"
			fxtbenv_usage_use
			return 1
			;;
		esac
		shift
	    done
	    product=$(fxtbenv_parse_product $target)
	    profile=$(fxtbenv_parse_profile $target)
	    if [ $? -ne 0 ]; then
		echo "$(fxtbenv_name): $(fxtbenv_warning) invalid profile name: $(fxtbenv_error $profile)"
		fxtbenv_usage_use
		return 1
	    fi
	    version=$(echo $profile | cut -d'@' -f1)
	    product_dir="$FXTBENV_HOME/${product}/versions/${version}"
	    if [ ! -d "$product_dir" ]; then
		echo "$(fxtbenv_name): $(fxtbenv_warning) not installed: $product $version"
		return 1
	    else
		profile_dir="$FXTBENV_HOME/${product}/profiles/${profile}"
		if [ ! -d "$profile_dir" ]; then
		    echo "$(fxtbenv_name): $(fxtbenv_warning) no such a profile($profile): $profile_dir"
		    if [ $FXTBENV_CREATE_PROFILE_DIR -eq 1 ]; then
			echo "$(fxtbenv_name): creating profile($profile): $profile_dir"
			mkdir -p $PROFILE_DIR
		    fi
		fi
		export FXTBENV_PROFILE=$profile
		export FXTBENV_PRODUCT=$product
	    fi
	    ;;
	list)
	    fxtbenv_list
	    ;;
	*)
	    $FXTBENV_HOME/bin/fxtbenvctl $*
	    ;;
    esac
}
