#!/bin/bash

fxtbenv_parse_profile() {
    profile=$(echo $1 | cut -d'-' -f2)
    case $profile in
	*@*)
	    echo $profile
	    return 0
	    ;;
	*)
	    echo $profile
	    return 1
	    ;;
    esac
}

fxtbenv_parse_product() {
    product=$(echo $1 | cut -d'-' -f1)
    echo $product
}

fxtbenv_usage_use () {
    echo "$(fxtbenv_name): fxtbenv use [--create|-c] firefox-VERSION@PROFILE"
    echo "$(fxtbenv_name): fxtbenv use [--create|-c] thunderbird-VERSION@PROFILE"
}

fxtbenv_name () {
    if [ $FXTBENV_DISABLE_ANSICOLOR -eq 1 ]; then
	echo "fxtbenv"
    else
	echo "\e[37m\e[42mfxtbenv\e[0m"
    fi
}

fxtbenv_warning () {
    if [ $FXTBENV_DISABLE_ANSICOLOR -eq 1 ]; then
	echo "warning"
    else
	echo "\e[37m\e[43mwarning\e[0m"
    fi
}

fxtbenv_error () {
    if [ $FXTBENV_DISABLE_ANSICOLOR -eq 1 ]; then
	echo "$1"
    else
	echo "\e[37m\e[41m$1\e[0m"
    fi
}

fxtbenv () {
    if [ -z "$FXTBENV_HOME" ]; then
	export FXTBENV_HOME=$HOME/.fxtbenv
    fi
    case $1 in
	use)
	    shift
	    target=""
	    while [ $# -gt 0 ]; do
		case $1 in
		    --create|-c)
			FXTBENV_CREATE_PROFILE_DIR=1
			;;
		    firefox-*|thunderbird-*)
			target=$1
			;;
		    *)
			echo "$(fxtbenv_name):  invalid argument: $(fxtbenv_error $1)"
			fxtbenv_usage_use
			return 1
			;;
		esac
		shift
	    done
	    product=$(fxtbenv_parse_product $target)
		profile=$(echo $1 | cut -d'-' -f2)
		version=$(echo $profile | cut -d'@' -f1)
		product_dir="$FXTBENV_HOME/${product}/versions/${version}"
		if [ ! -d "$product_dir" ]; then
		    echo "Not installed: $product $version"
		    return 1
		else
		    PROFILE_DIR="$FXTBENV_HOME/${product}/profiles/${profile}"
		    if [ ! -d "$PROFILE_DIR" ]; then
			echo "No such a profile($profile): $PROFILE_DIR"
			mkdir -p $PROFILE_DIR
		    fi
		    export FXTBENV_PROFILE=$profile
		    export FXTBENV_PRODUCT=$product
		fi
	    ;;
	*)
	    $FXTBENV_HOME/bin/fxtbenvctl $*
	    ;;
    esac
}
